# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/
    - job-hackers.json
    
stages:
  - build
  - deploy

build-members:
  image: node:10.16.0
  stage: build
  script:
    - npm ci
    - npm run build
    - cat job-hackers.json

deploy-to-production:
  image: docker:latest
  stage: deploy
  only:
    - master
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build -t registry.gitlab.com/hackyourjob-community/membres .
    - docker push registry.gitlab.com/hackyourjob-community/membres
